var imagePaths = {
  "vanilla": "img/vanilla.jpg",
  "chocolate": "img/chocolate.jpg",
  "strawberry": "img/strawberry.jpg",
  "mint": "img/mint.jpg",
  "coffee": "img/coffee.jpg",
  "hazelnut": "img/hazelnut.jpg",
  "cookies": "img/cookies.jpg",
  "banana": "img/banana.jpg",
};

var presetTexts = {
  "vanilla_chocolate": "The combination of chocolate and vanilla ice cream offers a classic and complementary contrast of flavors. The velvety richness of chocolate intertwines with the smooth and mellow essence of vanilla, creating a well-balanced and indulgent taste experience that caters to both chocolate enthusiasts and vanilla lovers. Each scoop provides a harmonious blend, making it a timeless and satisfying choice for those seeking a deliciously familiar dessert.",
  "chocolate_vanilla": "The combination of chocolate and vanilla ice cream offers a classic and complementary contrast of flavors. The velvety richness of chocolate intertwines with the smooth and mellow essence of vanilla, creating a well-balanced and indulgent taste experience that caters to both chocolate enthusiasts and vanilla lovers. Each scoop provides a harmonious blend, making it a timeless and satisfying choice for those seeking a deliciously familiar dessert.",
  "vanilla_strawberry": "The pairing of vanilla and strawberry ice cream results in a delightful blend of creamy sweetness and fruity vibrancy. The smooth, mellow tones of vanilla complement the bright, juicy flavor of strawberries, creating a harmonious and refreshing taste that's both comforting and reminiscent of a classic summer treat. Together, they offer a perfect balance for those seeking a fusion of creamy richness and fresh fruitiness in every bite.",
  "strawberry_vanilla": "The pairing of vanilla and strawberry ice cream results in a delightful blend of creamy sweetness and fruity vibrancy. The smooth, mellow tones of vanilla complement the bright, juicy flavor of strawberries, creating a harmonious and refreshing taste that's both comforting and reminiscent of a classic summer treat. Together, they offer a perfect balance for those seeking a fusion of creamy richness and fresh fruitiness in every bite.",
  "vanilla_mint": "The combination of vanilla and mint chocolate chip ice cream creates a delightful contrast of flavors. The creamy, mellow vanilla serves as a soothing base, while the refreshing burst of mint and the crunch of chocolate chips add a vibrant and playful twist, offering a harmonious blend of soothing and invigorating sensations in each scoop.",
  "mint_vanilla": "The combination of vanilla and mint chocolate chip ice cream creates a delightful contrast of flavors. The creamy, mellow vanilla serves as a soothing base, while the refreshing burst of mint and the crunch of chocolate chips add a vibrant and playful twist, offering a harmonious blend of soothing and invigorating sensations in each scoop.",
  "vanilla_coffee": "The pairing of vanilla and coffee ice cream offers a delightful mix of comforting familiarity and rich, bold flavors. The smooth, creamy vanilla provides a subtle sweetness that beautifully complements the robust, aromatic notes of coffee, resulting in a harmonious and sophisticated taste experience that caters to both classic dessert lovers and coffee aficionados.",
  "coffee_vanilla": "The pairing of vanilla and coffee ice cream offers a delightful mix of comforting familiarity and rich, bold flavors. The smooth, creamy vanilla provides a subtle sweetness that beautifully complements the robust, aromatic notes of coffee, resulting in a harmonious and sophisticated taste experience that caters to both classic dessert lovers and coffee aficionados.",
  "vanilla_hazelnut": "The smooth, classic vanilla undertones provide a familiar backdrop, while the hazelnut adds a subtle, toasty flavor that elevates the overall taste experience. This combination strikes a perfect balance between creamy and nutty, creating a delightful and sophisticated treat for those who enjoy a blend of timeless and nuanced flavors.",
  "hazelnut_vanilla": "The smooth, classic vanilla undertones provide a familiar backdrop, while the hazelnut adds a subtle, toasty flavor that elevates the overall taste experience. This combination strikes a perfect balance between creamy and nutty, creating a delightful and sophisticated treat for those who enjoy a blend of timeless and nuanced flavors.",
  "vanilla_cookies": "The combination of vanilla and cookies and cream ice cream offers a wonderful contrast of simplicity and indulgence. The creamy, subtle sweetness of vanilla intertwines with the rich, crunchy bits of cookie, creating a delightful blend of familiar comfort and the playful surprise of cookie pieces in every scoop. Together, they form a classic and satisfying treat for those seeking a balance between smoothness and a touch of texture.",
  "cookies_vanilla": "The combination of vanilla and cookies and cream ice cream offers a wonderful contrast of simplicity and indulgence. The creamy, subtle sweetness of vanilla intertwines with the rich, crunchy bits of cookie, creating a delightful blend of familiar comfort and the playful surprise of cookie pieces in every scoop. Together, they form a classic and satisfying treat for those seeking a balance between smoothness and a touch of texture.",
  "vanilla_banana": "The pairing of vanilla and banana ice cream creates a harmonious blend of creamy sweetness and fruity richness. The smooth, mellow tones of vanilla perfectly complement the natural sweetness and creamy texture of ripe bananas, offering a comforting and delightful flavor combination that feels both familiar and refreshing with each spoonful.",
  "banana_vanilla": "The pairing of vanilla and banana ice cream creates a harmonious blend of creamy sweetness and fruity richness. The smooth, mellow tones of vanilla perfectly complement the natural sweetness and creamy texture of ripe bananas, offering a comforting and delightful flavor combination that feels both familiar and refreshing with each spoonful.",
  "chocolate_strawberry": "The pairing of chocolate and strawberry ice cream creates a luscious fusion of rich, velvety cocoa and sweet, juicy berry goodness. The deep, indulgent chocolate notes complement the vibrant and fruity essence of the strawberries, resulting in a well-rounded and satisfying flavor profile. Together, they form a classic combination that offers a delightful balance of sweetness and decadence in every spoonful.",
  "strawberry_chocolate": "The pairing of chocolate and strawberry ice cream creates a luscious fusion of rich, velvety cocoa and sweet, juicy berry goodness. The deep, indulgent chocolate notes complement the vibrant and fruity essence of the strawberries, resulting in a well-rounded and satisfying flavor profile. Together, they form a classic combination that offers a delightful balance of sweetness and decadence in every spoonful.",
  "chocolate_mint": "Combining chocolate and mint chocolate chip ice cream results in a symphony of rich cocoa intertwining with the refreshing burst of mint. The deep, velvety chocolate merges with the cool mint and the playful crunch of chocolate chips, creating a delightful contrast that's both indulgent and invigorating, appealing to those who crave a harmonious blend of decadence and freshness in every scoop.",
  "mint_chocolate": "Combining chocolate and mint chocolate chip ice cream results in a symphony of rich cocoa intertwining with the refreshing burst of mint. The deep, velvety chocolate merges with the cool mint and the playful crunch of chocolate chips, creating a delightful contrast that's both indulgent and invigorating, appealing to those who crave a harmonious blend of decadence and freshness in every scoop.",
  "chocolate_coffee": "The fusion of chocolate and coffee ice cream delivers a dynamic duo of bold flavors. The rich, robust essence of coffee harmonizes with the deep, indulgent cocoa, creating a luxurious and complex taste experience that's perfect for those seeking a combination of intense flavors and a touch of indulgence in each spoonful.",
  "coffee_chocolate": "The fusion of chocolate and coffee ice cream delivers a dynamic duo of bold flavors. The rich, robust essence of coffee harmonizes with the deep, indulgent cocoa, creating a luxurious and complex taste experience that's perfect for those seeking a combination of intense flavors and a touch of indulgence in each spoonful.",
  "chocolate_hazelnut": "Blending chocolate and hazelnut ice cream yields a delightful fusion of rich cocoa and nutty sweetness. The decadent chocolate intertwines with the toasty, aromatic essence of hazelnuts, creating a luxurious and balanced flavor profile that satisfies both chocolate lovers and those craving a delightful nutty undertone in their dessert.",
  "hazelnut_chocolate": "Blending chocolate and hazelnut ice cream yields a delightful fusion of rich cocoa and nutty sweetness. The decadent chocolate intertwines with the toasty, aromatic essence of hazelnuts, creating a luxurious and balanced flavor profile that satisfies both chocolate lovers and those craving a delightful nutty undertone in their dessert.",
  "chocolate_cookies": "Combining chocolate and cookies and cream ice cream creates a delightful contrast of rich cocoa and crunchy cookie bits. The indulgent chocolate merges with the playful mix of cookie pieces, offering a satisfying blend of velvety smoothness and delightful texture in every scoop, making it a treat that's both comforting and exciting for those who enjoy a bit of crunch with their creamy dessert.",
  "cookies_chocolate": "Combining chocolate and cookies and cream ice cream creates a delightful contrast of rich cocoa and crunchy cookie bits. The indulgent chocolate merges with the playful mix of cookie pieces, offering a satisfying blend of velvety smoothness and delightful texture in every scoop, making it a treat that's both comforting and exciting for those who enjoy a bit of crunch with their creamy dessert.",
  "chocolate_banana": "This combination offers a delightful harmony of rich cocoa and sweet, creamy banana flavors. The velvety chocolate contributes a decadent and slightly bitter note, while the natural sweetness and subtle tanginess of the banana create a well-balanced and indulgent treat. This combination is likely to be enjoyed by individuals who appreciate a harmonious blend of decadence and fruity creaminess.",
  "banana_chocolate": "This combination offers a delightful harmony of rich cocoa and sweet, creamy banana flavors. The velvety chocolate contributes a decadent and slightly bitter note, while the natural sweetness and subtle tanginess of the banana create a well-balanced and indulgent treat. This combination is likely to be enjoyed by individuals who appreciate a harmonious blend of decadence and fruity creaminess.",
  "strawberry_mint": "The combination of strawberry and mint chocolate chip ice cream offers a refreshing balance of fruity sweetness and invigorating mint. The vibrant strawberry flavor intertwines with the cool freshness of mint and the playful crunch of chocolate chips, creating a delightful contrast that's both fruity and refreshing, appealing to those who enjoy a fusion of bright fruitiness with a hint of coolness in their dessert.",
  "mint_strawberry": "The combination of strawberry and mint chocolate chip ice cream offers a refreshing balance of fruity sweetness and invigorating mint. The vibrant strawberry flavor intertwines with the cool freshness of mint and the playful crunch of chocolate chips, creating a delightful contrast that's both fruity and refreshing, appealing to those who enjoy a fusion of bright fruitiness with a hint of coolness in their dessert.",
  "strawberry_coffee": "Combining strawberry and coffee ice cream brings a unique blend of fruity sweetness and bold, aromatic flavors. The vibrant tanginess of strawberries harmonizes surprisingly well with the richness of coffee, offering a delightful contrast that's both refreshing and complex, appealing to those who appreciate a fusion of fruity notes with a deep, robust coffee undertone in their dessert.",
  "coffee_strawberry": "Combining strawberry and coffee ice cream brings a unique blend of fruity sweetness and bold, aromatic flavors. The vibrant tanginess of strawberries harmonizes surprisingly well with the richness of coffee, offering a delightful contrast that's both refreshing and complex, appealing to those who appreciate a fusion of fruity notes with a deep, robust coffee undertone in their dessert.",
  "strawberry_hazelnut": "Blending strawberry and hazelnut ice cream results in a fascinating blend of fruity brightness and nutty richness. The sweet, tangy essence of strawberries pairs unexpectedly well with the toasty, aromatic flavor of hazelnuts, creating a harmonious and intriguing taste experience that's both refreshing and subtly indulgent, appealing to those seeking a unique fusion of fruitiness with a hint of nuttiness in their dessert.",
  "hazelnut_strawberry": "Blending strawberry and hazelnut ice cream results in a fascinating blend of fruity brightness and nutty richness. The sweet, tangy essence of strawberries pairs unexpectedly well with the toasty, aromatic flavor of hazelnuts, creating a harmonious and intriguing taste experience that's both refreshing and subtly indulgent, appealing to those seeking a unique fusion of fruitiness with a hint of nuttiness in their dessert.",
  "strawberry_cookies": "The combination of strawberry and cookies and cream ice cream offers a delightful mix of fruity sweetness and crunchy cookie goodness. The vibrant strawberry flavor complements the playful mix of cookie pieces, creating a harmonious blend of fruity notes and textured bites in every scoop, making it a treat that's both refreshing and satisfying for those seeking a fusion of fruitiness and crunchiness in their dessert.",
  "cookies_strawberry": "The combination of strawberry and cookies and cream ice cream offers a delightful mix of fruity sweetness and crunchy cookie goodness. The vibrant strawberry flavor complements the playful mix of cookie pieces, creating a harmonious blend of fruity notes and textured bites in every scoop, making it a treat that's both refreshing and satisfying for those seeking a fusion of fruitiness and crunchiness in their dessert.",
  "strawberry_banana": "The combination of strawberry and banana ice cream creates a delicious symphony of sweet and fruity flavors. The natural sweetness of ripe strawberries blends seamlessly with the creamy, mellow notes of banana, resulting in a refreshing and satisfying taste experience. The two fruits complement each other, offering a delightful balance that is both creamy and reminiscent of a fresh fruit medley.",
  "banana_strawberry": "The combination of strawberry and banana ice cream creates a delicious symphony of sweet and fruity flavors. The natural sweetness of ripe strawberries blends seamlessly with the creamy, mellow notes of banana, resulting in a refreshing and satisfying taste experience. The two fruits complement each other, offering a delightful balance that is both creamy and reminiscent of a fresh fruit medley.",
  "mint_coffee": "The combination of mint chocolate chip and coffee ice cream creates a tantalizing contrast of cool, refreshing mint with the bold richness of coffee. Together, they form a dynamic duo that caters to those who appreciate a blend of invigorating mint and the robust flavor of coffee in a single, indulgent scoop.",
  "coffee_mint": "The combination of mint chocolate chip and coffee ice cream creates a tantalizing contrast of cool, refreshing mint with the bold richness of coffee. Together, they form a dynamic duo that caters to those who appreciate a blend of invigorating mint and the robust flavor of coffee in a single, indulgent scoop.",
  "mint_hazelnut": "The blend of mint chocolate chip and hazelnut ice cream presents a fusion of refreshing mint with the nutty richness of hazelnuts. The cool, invigorating mint swirls amidst the toasty, aromatic hazelnut flavor, creating a unique contrast that's both refreshing and indulgent, appealing to those who enjoy the interplay of coolness and nutty undertones in their dessert.",
  "hazelnut_mint": "The blend of mint chocolate chip and hazelnut ice cream presents a fusion of refreshing mint with the nutty richness of hazelnuts. The cool, invigorating mint swirls amidst the toasty, aromatic hazelnut flavor, creating a unique contrast that's both refreshing and indulgent, appealing to those who enjoy the interplay of coolness and nutty undertones in their dessert.",
  "mint_cookies": "Combining mint chocolate chip and cookies and cream ice cream offers a playful contrast of refreshing mint with the delightful crunch of cookie bits. The invigorating mint intertwines with the playful mix of cookie pieces, creating a harmonious blend of coolness and textured bites in every scoop, offering a delightful balance that's both refreshing and pleasantly textured for those seeking a fusion of minty freshness and cookie crunchiness in their dessert.",
  "cookies_mint": "Combining mint chocolate chip and cookies and cream ice cream offers a playful contrast of refreshing mint with the delightful crunch of cookie bits. The invigorating mint intertwines with the playful mix of cookie pieces, creating a harmonious blend of coolness and textured bites in every scoop, offering a delightful balance that's both refreshing and pleasantly textured for those seeking a fusion of minty freshness and cookie crunchiness in their dessert.",
  "mint_banana": "The combination of mint chocolate chip and banana ice cream delivers a surprising blend of refreshing mint with creamy banana sweetness. The cool, invigorating mint enhances the smoothness of the banana, creating a unique contrast that's both refreshing and indulgent, appealing to those who enjoy the fusion of minty freshness with the creamy richness of banana in their dessert.",
  "banana_mint": "The combination of mint chocolate chip and banana ice cream delivers a surprising blend of refreshing mint with creamy banana sweetness. The cool, invigorating mint enhances the smoothness of the banana, creating a unique contrast that's both refreshing and indulgent, appealing to those who enjoy the fusion of minty freshness with the creamy richness of banana in their dessert.",
  "coffee_hazelnut": "Combining coffee and hazelnut ice cream results in a harmonious union of robust coffee notes and the nutty richness of hazelnuts. The bold, aromatic coffee intertwines seamlessly with the toasty, flavorful hazelnut, creating a sophisticated and indulgent taste experience that's both deeply aromatic and subtly sweet, catering to those who enjoy a blend of coffee's depth with the nutty undertones in their dessert.",
  "hazelnut_coffee": "Combining coffee and hazelnut ice cream results in a harmonious union of robust coffee notes and the nutty richness of hazelnuts. The bold, aromatic coffee intertwines seamlessly with the toasty, flavorful hazelnut, creating a sophisticated and indulgent taste experience that's both deeply aromatic and subtly sweet, catering to those who enjoy a blend of coffee's depth with the nutty undertones in their dessert.",
  "coffee_cookies": "Pairing coffee and cookies and cream ice cream yields a delightful contrast of robust coffee flavors with the playful crunch of cookie pieces. The bold, aromatic essence of coffee intertwines with the mix of cookie bits, offering a harmonious blend of rich coffee notes and textured bites in every scoop, creating an enjoyable experience for those seeking a fusion of coffee depth and cookie crunchiness in their dessert.",
  "cookies_coffee": "Pairing coffee and cookies and cream ice cream yields a delightful contrast of robust coffee flavors with the playful crunch of cookie pieces. The bold, aromatic essence of coffee intertwines with the mix of cookie bits, offering a harmonious blend of rich coffee notes and textured bites in every scoop, creating an enjoyable experience for those seeking a fusion of coffee depth and cookie crunchiness in their dessert.",
  "coffee_banana": "Combining coffee and banana ice cream results in a surprising yet delightful fusion of bold, aromatic coffee with creamy banana sweetness. The robust coffee enhances the natural richness of banana, creating a unique contrast that's both invigorating and indulgent, offering a pleasant harmony for those who enjoy the combination of coffee's depth with the creamy sweetness of banana in their dessert.",
  "banana_coffee": "Combining coffee and banana ice cream results in a surprising yet delightful fusion of bold, aromatic coffee with creamy banana sweetness. The robust coffee enhances the natural richness of banana, creating a unique contrast that's both invigorating and indulgent, offering a pleasant harmony for those who enjoy the combination of coffee's depth with the creamy sweetness of banana in their dessert.",
  "hazelnut_cookies": "Pairing hazelnut and cookies and cream ice cream creates a delightful fusion of nutty richness with playful crunchiness. The toasty flavor of hazelnut blends beautifully with the mix of cookie pieces, offering a harmonious balance of nutty undertones and textured bites in every scoop, creating a satisfying experience for those seeking a combination of nutty richness and delightful cookie crunch in their dessert.",
  "cookies_hazelnut": "Pairing hazelnut and cookies and cream ice cream creates a delightful fusion of nutty richness with playful crunchiness. The toasty flavor of hazelnut blends beautifully with the mix of cookie pieces, offering a harmonious balance of nutty undertones and textured bites in every scoop, creating a satisfying experience for those seeking a combination of nutty richness and delightful cookie crunch in their dessert.",
  "hazelnut_banana": "Blending hazelnut and banana ice cream results in a unique marriage of nutty richness with creamy sweetness. The toasty, aromatic notes of hazelnut complement the natural richness of banana, creating a delightful contrast that's both indulgent and subtly nutty, appealing to those who enjoy the combination of nuttiness with the creamy sweetness of banana in their dessert.",
  "banana_hazelnut": "Blending hazelnut and banana ice cream results in a unique marriage of nutty richness with creamy sweetness. The toasty, aromatic notes of hazelnut complement the natural richness of banana, creating a delightful contrast that's both indulgent and subtly nutty, appealing to those who enjoy the combination of nuttiness with the creamy sweetness of banana in their dessert.",
  "banana_cookies": "Combining banana and cookies and cream ice cream offers a playful blend of creamy sweetness with delightful crunchiness. The smooth, mellow banana flavor intertwines with the mix of cookie pieces, creating a harmonious balance of creamy banana notes and textured bites in every scoop, providing a satisfying experience for those seeking a fusion of fruity creaminess and enjoyable cookie crunch in their dessert.",
  "cookies_banana": "Combining banana and cookies and cream ice cream offers a playful blend of creamy sweetness with delightful crunchiness. The smooth, mellow banana flavor intertwines with the mix of cookie pieces, creating a harmonious balance of creamy banana notes and textured bites in every scoop, providing a satisfying experience for those seeking a fusion of fruity creaminess and enjoyable cookie crunch in their dessert.",

};

function updateImages() {
  var dropdown1 = document.getElementById("dropdown1");
  var dropdown2 = document.getElementById("dropdown2");
  var leftImage = document.getElementById("leftImage");
  var rightImage = document.getElementById("rightImage");

  var selectedValue1 = dropdown1.value;
  var selectedValue2 = dropdown2.value;

  // Set the src attribute of the leftImage based on the selected value in dropdown1
  leftImage.src = imagePaths[selectedValue1] || "";

  // Set the src attribute of the rightImage based on the selected value in dropdown2
  rightImage.src = imagePaths[selectedValue2] || "";
}

function updateText() {
  var dropdown1 = document.getElementById("dropdown1");
  var dropdown2 = document.getElementById("dropdown2");
  var resultDiv = document.getElementById("result");

  var selectedValue1 = dropdown1.value;
  var selectedValue2 = dropdown2.value;

  // Concatenate selected values to form a key for the presetTexts object
  var combinationKey = selectedValue1 + "_" + selectedValue2;

  // Check if the combination key exists in the presetTexts object
  if (presetTexts.hasOwnProperty(combinationKey)) {
    // Display the corresponding preset text
    resultDiv.innerHTML = presetTexts[combinationKey];
  } else {
    resultDiv.innerHTML = "Please select two unique flavors.";
  }
}